config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  resources :users do
    resources :posts do
      member do
        post 'like'
      end
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, required: true
  belongs_to :user, class_name: 'User', foreign_key: 'author_id', required: true

  after_create :update_comment_counter

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id', class_name: 'User'
  belongs_to :post, foreign_key: 'post_id'

  validates :author_id, presence: true
  validates :post_id, presence: true

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  scope :most_recent_comments, lambda { |limit = 5|
    includes(:comments).order('comments.created_at DESC').limit(limit)
  }

  def most_recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def comment_counter
    comments.count
  end

  def like_counter
    likes.count
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def validation_comments_counter
    return unless comments_counter.present? && (!comments_counter.is_a?(Integer) || comments_counter.negative?)

    errors.add(:comments_counter, 'It must be a number greater than or equal to zero') unless comments_counter.zero?
  end

  def validation_likes_counter
    return unless likes_counter.present? && (!likes_counter.is_a?(Integer) || likes_counter.negative?)

    errors.add(:likes_counter, 'It must be a number greater than or equal to zero') unless likes_counter.zero?
  end

  def initialize_comments_counter
    self.comments_counter ||= 0
  end

  def initialize_likes_counter
    self.likes_counter ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :name, presence: true
  attribute :post_counter, :integer, default: 0

  def recent_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = # ... set the user
      @post = Post.find(params[:post_id]) # Assuming you have a post_id parameter
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      redirect_to user_post_path(@user, @post), alert: 'Error creating comment.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
    @like = @post.likes.build(user: @user)

    if @like.save
      redirect_to user_posts_path(@user)
    else
      redirect_to user_posts_path(@user), alert: 'Error creating like.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(posts: :comments).find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = Post.new(post_params)
    @post.author = @user

    if @post.save
      redirect_to user_posts_path(@user), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def like
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @like = Like.new(user: @user, post: @post)

    if @like.save
      redirect_to user_post_path(@user, @post), notice: 'Post liked successfully.'
    else
      redirect_to user_post_path(@user, @post), alert: 'Error liking the post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [current_user, @post, Comment.new], local: true) do |form| %>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <%= form.submit 'Add Comment' %>
<% end %>

app/views/comments/_new.html.erb
<%= form_with(model: [current_user, @post, Comment.new], local: true) do |form| %>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <%= form.submit 'Add Comment' %>
<% end %>

app/views/comments/new.html.erb
<%= form_with(model: [current_user, @post, Comment.new], local: true) do |form| %>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <%= form.submit 'Add Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="user-navigation">
  <a href="<%= user_path(@user) %>">
    <button class="back-btn">⬅</button>
  </a>
</div>
<section class="user-profile-page">
  <div class='post-user-info'>
    <% if @user.photo.present? %>
      <%= image_tag @user.photo, alt: @user.name, class: 'user-thumbnail' %>
    <% else %>
      <span class="user-thumbnail placeholder">No Photo</span>
    <% end %>
    <p>Name: <%= @user.name %></p>
    <p>Number of Posts: <%= @user.posts.count %></p>
  </div>
  <div class="user-posts">
    <% if @user.posts.any? %>
      <ul class="user-posts-info">
        <% Post.most_recent_comments(5).each do |post| %>
        <li>
          <%= link_to user_post_path(@user, post) do %>
            <h3><%= post.title %></h3>
            <p><%= post.text %></p>
          <% end %>
        </li>

  <div class="counters">
    <li>Comments: <%= post.comment_counter %></li>
    <li>Likes: <%= post.like_counter %></li>
  </div>

  <% post.most_recent_comments.each do |comment| %>
    <div class="comment">
      <strong><%= comment.user.name %>:</strong>
      <%= comment.text %>
    </div>
  <% end %>
<% end %>

      </ul>

      <% if @user.posts.count > 3 %>
        <%= link_to 'Show More', user_posts_path(@user) %>
      <% end %>
    <% else %>
      <p>No posts available.</p>
    <% end %>
  </div>
  <a href="<%= users_path() %>" class='pagination'>
    <button class='pagination-btn'>Pagination</button>
  </a>
</section>

app/views/posts/new.html.erb
<h1>Create New Post!</h1>
<hr class="col-md-6 mb-5">

<%= form_with(model: @post, url: user_posts_path(current_user)) do |form| %>
  <div class="col-md-6 mb-3">
    <%= form.label :title, style: "display: block", class: "fw-bold form-label" %>
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

  <div class="col-md-6 mb-3">
    <%= form.label :text, style: "display: block", class: "fw-bold form-label" %>
    <%= form.text_area :text, class: "form-control", placeholder: "Content", rows: "3" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Create Post", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="user-navigation">
  <a href="<%= user_posts_path(@user) %>">
    <button class="back-btn">⬅</button>
  </a>
</div>
<section class="single-post-page">
  <div class="single-post-info">
    <div class="single-post-header">
      <h1><%= @post.title %> by <%= @user.name %></h1>
      <div class="comments-likes">
        <p>Comments: <%= @post.comment_counter %></p>
        <p>Likes: <%= @post.like_counter %></p>
        <%= button_to 'Like', like_user_post_path(@post.author, @post), method: :post, class: 'like-button' %>
      </div>
    </div>
    </div>
    <p><%= @post.text %></p>
  </div>

  <div class="comments-section">
    <h2>Comments:</h2>
    <% if @post.comments.any? %>
      <% @post.comments.each do |comment| %>
        <div class="comment">
          <strong><%= comment.user.name %>:</strong>
          <%= comment.text %>
        </div>
      <% end %>
    <% else %>
      <p>No comments available.</p>
    <% end %>

  </div>

  <div class="new-comment-form">
    <%= render 'comments/new', post: @post %>
  </div>
</section>

app/views/users/index.html.erb
<section class="home-options">
  <h1>List of all users</h1>
  <div class="logout">
    <% if user_signed_in? %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    <% end %>
  </div>
</section>
<ul class="users-list">
  <% @users.each do |user| %>
    <li class="user-list">
      <% if user.photo.present? %>
        <%= image_tag user.photo, alt: user.name, class: 'user-thumbnail' %>
      <% else %>
        <span class="user-thumbnail placeholder">No Photo</span>
      <% end %>
      <%= link_to user.name, user_path(user) %>
      <span class="post-count">Number of posts: <%= user.posts.count %></span>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%# <h1>User Profile</h1> %>
<div class="user-navigation">
  <a href="<%= users_path %>">
    <button class="back-btn">⬅</button>
  </a>
</div>
<section class="user-profile-page">
  <div class="user-profile">
    <% if @user.photo.present? %>
      <%= image_tag @user.photo, alt: @user.name, class: 'user-thumbnail' %>
    <% else %>
      <span class="user-thumbnail placeholder">No Photo</span>
    <% end %>
    <p><%= @user.name %></p>
    <p>Number of Posts: <%= @user.posts.count %></p>
  </div>
  <div class="user-bio">
    <h3>Bio:</h3>
    <p><%= @user.bio %></p>
  </div>

  <div>
    <%= link_to 'Add Post', new_user_post_path(@user), class: 'add-post-button' %>
  </div>
  
  <div class="user-posts">
    <h2><%= @user.name %>`s posts</h2>
    <% if @user.posts.any? %>
      <ul class="user-posts-info">
        <% @user.recent_posts.limit(3).each do |post| %>
          <h3><%= post.title %></h3>
          <li><%= post.text %></li>
          <div class="counters">
            <li>Comments:<%= post.comments_counter %></li>
            <li>Likes:<%= post.likes_counter %></li>
          </div>
        <% end %>
      </ul>
    <% else %>
      <p>No posts available.</p>
    <% end %>

  </div>
  <div>
    <%= link_to 'See All Posts', user_posts_path(@user), class: 'see-all-button' %>
  </div>
</section>